
[functions.sendEmailQr]
enabled = true
verify_jwt = false
import_map = "./functions/sendEmailQr/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/sendEmailQr/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/sendEmailQr/*.html" ]

[functions.sendEmailQrs]
enabled = true
verify_jwt = true
import_map = "./functions/sendEmailQrs/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/sendEmailQrs/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/sendEmailQrs/*.html" ]
