name: tefa_parkir
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  qr_code_scanner:
    path: ./plugins/qr_code_scanner

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.9.1
  camera: ^0.11.0+2
  qr_flutter: ^4.1.0
  image_picker: ^1.0.4
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
